repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: no-commit-to-branch # prevent direct commits to protected branches
        args: ["--branch", "main"]
      - id: check-yaml # validate YAML syntax
        args: ["--unsafe"] # allow custom tags
      - id: check-toml # validate TOML syntax
      - id: end-of-file-fixer # ensure files end with a newline
      - id: trailing-whitespace # remove trailing whitespace from lines
        exclude: \.ambr$

  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.8
    hooks:
      - id: fix-smartquotes
      - id: fix-spaces

  - repo: local
    hooks:
      - id: deepagents
        name: format and lint deepagents
        language: system
        entry: make -C libs/deepagents format lint
        files: ^libs/deepagents/
        pass_filenames: false
      - id: deepagents-cli
        name: format and lint deepagents-cli
        language: system
        entry: make -C libs/cli format lint
        files: ^libs/cli/
        pass_filenames: false
      - id: harbor
        name: format and lint harbor
        language: system
        entry: make -C libs/harbor format lint
        files: ^libs/harbor/
        pass_filenames: false
      - id: acp
        name: format and lint acp
        language: system
        entry: make -C libs/acp format lint
        files: ^libs/acp/
        pass_filenames: false
