repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: no-commit-to-branch
        args: ["--branch", "master"]
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: \.ambr$

  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.8
    hooks:
      - id: fix-smartquotes
      - id: fix-spaces

  - repo: local
    hooks:
      - id: deepagents
        name: format and lint deepagents
        language: system
        entry: make -C libs/deepagents format lint
        files: ^libs/deepagents/
        pass_filenames: false
      - id: deepagents-cli
        name: format and lint deepagents-cli
        language: system
        entry: make -C libs/deepagents-cli format lint
        files: ^libs/deepagents-cli/
        pass_filenames: false
      - id: harbor
        name: format and lint harbor
        language: system
        entry: make -C libs/harbor format lint
        files: ^libs/harbor/
        pass_filenames: false
      - id: acp
        name: format and lint acp
        language: system
        entry: make -C libs/acp format lint
        files: ^libs/acp/
        pass_filenames: false
